apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soc-agent.fullname" . }}-frontend
  labels:
    {{- include "soc-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: soc-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: soc-frontend
        release: {{ .Release.Name }}
        {{- include "soc-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_HOST
              value: "{{ include "soc-agent.fullname" . }}-backend"
            - name: BACKEND_PORT
              value: "{{ .Values.backend.service.port }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

